services:
  azurite-input:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: azurite-input
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    environment:
      - AZURITE_ACCOUNTS=devstoreaccount1:key1
    volumes:
      - ./azurite_data_input:/data
    networks:
      - mynetwork

  azurite-output:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: azurite-output
    ports:
      - "20000:10000"
      - "20001:10001"
      - "20002:10002"
    environment:
      - AZURITE_ACCOUNTS=devstoreaccount1:key1
    volumes:
      - ./azurite_data_output:/data
    networks:
      - mynetwork

  ci-agent:
    build:
      context: ./src/ci-agent
      dockerfile: Dockerfile.dev
    container_name: ci-agent
    ports:
      - "5001:5001"
    depends_on:
      - azurite-input
    env_file:
      - .env.local
    networks:
      - mynetwork

  ic-agent:
    build:
      context: ./src/ic-agent
      dockerfile: Dockerfile.dev
    container_name: ic-agent
    ports:
      - "5002:5002"
    depends_on:
      - azurite-output
    env_file:
      - .env.local
    networks:
      - mynetwork

  co-agent:
    build:
      context: ./src/co-agent
      dockerfile: Dockerfile.dev
    container_name: co-agent
    ports:
      - "5003:5003"
    env_file:
      - .env.local
    networks:
      - mynetwork

  
  lt-agent:
    build:
      context: ./src/lt-agent
      dockerfile: Dockerfile.dev
    container_name: lt-agent
    ports:
      - "5004:5004"
    env_file:
      - .env.local
    networks:
      - mynetwork

networks:
  mynetwork:
