services:
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: azurite
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    environment:
      - AZURITE_ACCOUNTS=devstoreaccount1:key1
    volumes:
      - ./azurite_data:/data
    networks:
      - mynetwork

  ci-agent:
    build:
      context: ./src/ci-agent
      dockerfile: Dockerfile.dev
    container_name: ci-agent
    ports:
      - "5001:5001"
    depends_on:
      - azurite
    environment:
      - AZURE_STORAGE_CONNECTION_STRING=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=key1;BlobEndpoint=http://azurite:10000/devstoreaccount1;
      - AZURE_STORAGE_CONTAINER_NAME=image-compression
      - SERVICE_BUS_CONNECTION_STRING=Endpoint=sb://localhost/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=local
      - SERVICE_BUS_QUEUE_NAME=image_compression_todo_queue
    networks:
      - mynetwork

volumes:
  sqlserverdata:


networks:
  mynetwork:
