version: '3.8'

services:
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: azurite
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    environment:
      - AZURITE_ACCOUNTS=devstoreaccount1:key1

    sqlserver:
      image: mcr.microsoft.com/mssql/server:2019-latest
      container_name: sqlserver
      environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=YourStrong!Passw0rd
      ports:
        - "1433:1433"

  servicebus:
    image: mcr.microsoft.com/azure-messaging/servicebus-emulator
    container_name: servicebus-compression-todo_queue
    ports:
      - "5672:5672"
      - "8081:8081"
    environment:
      - ACCEPT_EULA=Y



  ci-agent:
    build: ./src/ci-agent
    container_name: ci-agent
    ports:
      - "5001:5001"
    depends_on:
      - azurite
      - servicebus
    environment:
      - AZURE_STORAGE_CONNECTION_STRING=UseDevelopmentStorage=true; # local development link
    # - AZURE_STORAGE_CONNECTION_STRING="DefaultEndpointsProtocol=https;AccountName=myaccount;AccountKey=mykey;EndpointSuffix=core.windows.net" # Azure Storage Account
      - AZURE_STORAGE_CONTAINER_NAME=image_compression
      - SERVICE_BUS_CONNECTION_STRING=Endpoint=sb://localhost/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=local
      - SERVICE_BUS_QUEUE_NAME=image_compression_todo_queue
