version: '3.8'

services:
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: azurite
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    environment:
      - AZURITE_ACCOUNTS=devstoreaccount1:key1
    networks:
      - mynetwork

  sqlserver:
    image: mcr.microsoft.com/azure-sql-edge:1.0.7
    platform: "linux/amd64"
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql
    # - /Users/timburkei/Documents/project/05_kubernetes/src/ci-agent/mssql.conf:/var/opt/mssql/mssql.conf
    networks:
      - mynetwork

  servicebus:
    image: mcr.microsoft.com/azure-messaging/servicebus-emulator
    container_name: servicebus-compression-todo_queue
    ports:
      - "5672:5672"
      - "8081:8081"
    environment:
      - ACCEPT_EULA=Y
      - SQL_CONNECTION_STRING=Server=sqlserver;Database=master;User=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;
    networks:
      - mynetwork

  ci-agent:
    build:
      context: ./src/ci-agent
      dockerfile: Dockerfile.dev
    container_name: ci-agent
    ports:
      - "5001:5001"
    depends_on:
      - azurite
      - servicebus
      - sqlserver
    environment:
      - AZURE_STORAGE_CONNECTION_STRING=UseDevelopmentStorage=true; # local development link
      - AZURE_STORAGE_CONTAINER_NAME=image_compression
      - SERVICE_BUS_CONNECTION_STRING=Endpoint=sb://localhost/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=local
      - SERVICE_BUS_QUEUE_NAME=image_compression_todo_queue
    networks:
      - mynetwork

volumes:
  sqlserverdata:


networks:
  mynetwork:
