name: Deploy Images to GHCR

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy-agent-images:
    name: Push Docker images to GHCR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.AUTH_GITHUB_TOKEN }}
      - name: Build and push CI-Agent Docker image
        uses: docker/build-push-action@v3
        with:
            context: ./src/ci-agent
            file: ./src/ci-agent/Dockerfile
            push: true
            tags: ghcr.io/${{ github.repository_owner }}/ci-agent:latest
